# Generated by Django 4.1.10 on 2023-08-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=1000, null=True)),
                ('Origin', models.CharField(blank=True, choices=[('China', 'China'), ('Taiwan', 'Taiwan'), ('Vietnam', 'Vietnam'), ('South', 'South'), ('Korea', 'Korea'), ('Thailand', 'Thailand')], default=None, max_length=25)),
                ('Destination', models.CharField(blank=True, choices=[('New_York_City', 'New York City'), ('Kansas_City', 'Kansas City'), ('Dallas', 'Dallas'), ('Atlanta', 'Atlanta'), ('Chicago', 'Chicago')], default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50, null=True)),
                ('Description', models.TextField(max_length=50, null=True)),
                ('Media', models.FileField(blank=True, null=True, upload_to='')),
                ('Product_Type', models.CharField(choices=[('Choose One:', 'Choose'), ('Export', 'Export'), ('Import', 'Import')], default='Choose One:', max_length=20)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductsAndAccess.route')),
            ],
        ),
    ]
