# Generated by Django 4.1.10 on 2023-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetsCMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='LayoutType',
            new_name='Layout_Type',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='Active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='Background_Asset',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='Overlay_Asset',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
