# Generated by Django 4.1.10 on 2023-07-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetsCMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='mStatement',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
