# Generated by Django 4.1.10 on 2023-07-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetsCMS', '0002_sequence_mstatement_alter_sequence_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='votes',
        ),
    ]
