# Generated by Django 4.1.10 on 2023-07-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetsCMS', '0003_remove_sequence_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='pub_date',
        ),
    ]
