# Generated by Django 4.1.10 on 2023-07-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetsCMS', '0004_remove_playlist_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='mActive',
            field=models.BooleanField(null=True),
        ),
    ]
