# Generated by Django 4.1.10 on 2023-07-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetsCMS', '0005_playlist_mactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='mStatement',
        ),
        migrations.AddField(
            model_name='sequence',
            name='mOverlayAsset',
            field=models.FilePathField(null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='mStatement1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='mStatement2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='mStatement3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='mStatementOfPurpose',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
