# Generated by Django 4.1.10 on 2023-07-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetsCMS', '0006_remove_sequence_mstatement_sequence_moverlayasset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='mOverlayAsset',
            field=models.FilePathField(null=True, verbose_name='static/polls/images/background.png'),
        ),
    ]
