# Generated by Django 4.1.10 on 2023-07-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetsCMS', '0007_alter_sequence_moverlayasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='mOverlayAsset',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
