# Generated by Django 4.1.10 on 2023-07-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetsCMS', '0008_alter_sequence_moverlayasset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='mActive',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='mPlaylistName',
            new_name='PlaylistName',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='mOverlayAsset',
            new_name='OverlayAsset',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='mTitle',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='mStatement1',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='mStatement2',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='mStatement3',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='mStatementOfPurpose',
        ),
        migrations.AddField(
            model_name='sequence',
            name='Statement1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='Statement2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='Statement3',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='StatementOfPurpose',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
