# Generated by Django 4.1.10 on 2023-08-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Playlist_Name', models.CharField(max_length=50, null=True)),
                ('Active', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Layout_Type', models.CharField(choices=[('one', 'Layout One'), ('two', 'Layout Two')], default='one', max_length=5)),
                ('Background_Asset', models.FileField(blank=True, null=True, upload_to='')),
                ('Title', models.CharField(max_length=200)),
                ('Statement_1', models.TextField(max_length=1000, null=True)),
                ('Overlay_Asset', models.FileField(blank=True, null=True, upload_to='')),
                ('Map_Zone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('S', 'S'), ('T', 'T'), ('None', 'None')], default='None', max_length=4)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TwentyFourHourDay.playlist')),
            ],
        ),
    ]
